package com.relaya.demo.audit.domain;

public enum AuditEventType {
	INTAKE_SUBMITTED,
	ANALYSIS_STARTED,
	ANALYSIS_COMPLETED,
	ANALYSIS_FAILED,
	DRAFT_UPDATED,
	DRAFT_APPROVED,
	APPROVAL_INVALIDATED,
	BOARD_WRITE_REQUESTED,
	BOARD_WRITE_COMPLETED,
	BOARD_WRITE_FAILED
}